"""empty message

Revision ID: 26d9fc162642
Revises: b677cb2abdbc
Create Date: 2023-12-13 17:26:22.671150

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d9fc162642'
down_revision: Union[str, None] = 'b677cb2abdbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('assets', 'abbreviation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('abbreviation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'name')
    # ### end Alembic commands ###
