"""empty message

Revision ID: 2f7417b23762
Revises: 90bdb84fa01d
Create Date: 2023-12-05 18:55:21.892224

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7417b23762'
down_revision: Union[str, None] = '90bdb84fa01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
