"""empty message

Revision ID: 5bc96e547b89
Revises: 26d9fc162642
Create Date: 2023-12-13 17:27:41.481895

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc96e547b89'
down_revision: Union[str, None] = '26d9fc162642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('abbreviation', sa.String(), nullable=True))
    op.drop_column('assets', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'abbreviation')
    # ### end Alembic commands ###
