"""empty message

Revision ID: 6adb5405068f
Revises: 2e8333b2b1ee
Create Date: 2023-12-05 19:56:44.631263

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adb5405068f'
down_revision: Union[str, None] = '2e8333b2b1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
