"""empty message

Revision ID: b677cb2abdbc
Revises: fc4ac5f97a30
Create Date: 2023-12-13 00:06:56.456678

"""
from typing import Sequence, Union
import sqlalchemy_utils

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b677cb2abdbc'
down_revision: Union[str, None] = 'fc4ac5f97a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('image', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
